[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
bytesize = { version = "1.2.0" }
quick-xml = { version = "0.31.0", features = ["serialize"]}
csv = "1.3.0"
